# Generated by Django 6.0 on 2025-12-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeAccount', '0003_doctorslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='makeAccount.doctor'),
            preserve_default=False,
        ),
    ]
