# Generated by Django 6.0 on 2025-12-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeAccount', '0005_appointment_status_bill_feedback_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
